server:
  port: 8080

spring:
  application:
    name: app-tire-mg-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: prod
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis.backend.svc.cluster.local
    password: opredis@^1234!
    timeout: 3000ms
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: ${ACTUATOR_USER}  # Kubernetes Secret 필수
      password: ${ACTUATOR_PASSWORD}  # Kubernetes Secret 필수

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external-prod.backend.svc.cluster.local:5432/tiremsdb?prepareThreshold=1
  username: admin_user
  password: admin@^1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

notify:
  server:
    base-url: http://notify-service.backend.svc.cluster.local:8080
    send-path: /notify-service/api/v1/alarm/notify/send

molit:
  vehicle:
    api:
      url: https://linkstg.car365.go.kr/hub/kotsa
      service-id: AC1_ZA85_01
      cvmis-apikey: 7AA75EC3-917067ED-689C6D47-96345CA9
      private-key-password: test1234!
      public-key-base64: -----BEGIN CERTIFICATE-----
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhRENDQkZDZ0F3SUJBZ0lD
        QVdrd0RRWUpLb1pJaHZjTkFRRUxCUUF3WlRFTE1Ba0dBMVVFQmhNQ1MxSXhNREF1
        QmdOVkJBb00NCkowdHZjbVZoSUVsdVptOXliV0YwYVc5dUlFTmxjblJwWm1sallY
        UmxJRUYxZEdodmNtbDBlVEVWTUJNR0ExVUVDd3dNUVdOamNtVmsNCmFYUmxaRU5C
        TVEwd0N3WURWUVFEREFSemRtTmhNQjRYRFRJME1EVXdOekF4TVRNd01Wb1hEVE0w
        TURVd056QXhNVE13TVZvd2ZqRUwNCk1Ba0dBMVVFQmhNQ1MxSXhEVEFMQmdOVkJB
        b01CRXRKUTBFeEV6QVJCZ05WQkFzTUNteHBZMlZ1YzJWa1EwRXhEekFOQmdOVkJB
        c00NCkJsTkZVbFpGVWpFUk1BOEdBMVVFQ3d3SVMwbERRVlJGVTFReER6QU5CZ05W
        QkFzTUJsTkZVbFpGVWpFV01CUUdBMVVFQXd3TmRHVnoNCmRHTmxjblJmTURVd056
        Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUs5alVh
        OEtseG1SMFZOY3FpZEwNCk1QaE9WOGJSNE1RWmxkcGE5N01IakFnT201T0RVa0x4
        cVcrOWRZVS9zMDg3akZNbFo2Vjl4RnF3NFFEQng1UEdiRzJrbm9yNEo4eUgNCnZy
        MnAzY1NlUktjZkN4KzUyK3VVbnpOL1lNOEtjNXlPZ2ExcnM3YXJPSFkxaVRKdFJS
        c3B6Y0RiNzcrZ242ZnVCSGE0WmdCbEdEc2QNCm5kZjlxSm8xajk0TU1MeGRoKzdK
        UTFkaG1nMnpKQXhqU2F4MktKbjdnT3JPUDFIVDJEZXloWElyVW0rd08zSXp1Ris3
        S3dOQnpEcWINCjJRUjMwYWl6MWxvc2JMRnpFNmJ0R20vOWVIVm9KWFBCSnVxZzNW
        MnZHNmlwdENXL0ljdzZOMWRQWktGOEdwN0F5K3MxSDRtenQ1L0MNCk9zWHBHTzB6
        UlNuNDBLaUFqRDBDQXdFQUFhT0NBZ2N3Z2dJRE1IZ0dBMVVkSUFSeE1HOHdiUVlF
        VlIwZ0FEQmxNREFHQ0NzR0FRVUYNCkJ3SUJGaVJvZEhSd09pOHZkM2QzTG5KdmIz
        UmpZUzV2Y2k1cmNpOXlZMkV2WTNCekxtaDBiV3d3TVFZSUt3WUJCUVVIQWdJd0pR
        d2oNCjdMQ283SVM0NjR5QUlPeWVrT3VQbWV5d3FDRHNoSnpyc29Uc25ianNwcDNz
        aEp3d0RnWURWUjBQQVFIL0JBUURBZ1hnTUJ3R0ExVWQNCkVRUVZNQk9nRVFZSktv
        TWFqSnBFQ2dFQm9BUXdBZ3dBTUNZR0NDc0dBUVVGQndFQkJCb3dHREFXQmdnckJn
        RUZCUWN3QVlZS2IyTnoNCmNDZHpYMVZTVERBZEJnTlZIUTRFRmdRVWhjNUJSWTIz
        QjRLVHFSdzFvSWxTZlNQUkhDNHdnWndHQTFVZEl3U0JsRENCa1lBVU9qa24NCmF3
        aTZjMDExV2NlNTlvRVBPamZtUlJPaGRhUnpNSEV4Q3pBSkJnTlZCQVlUQWt0U01U
        QXdMZ1lEVlFRS0RDZExiM0psWVNCSmJtWnYNCmNtMWhkR2x2YmlCRFpYSjBhV1pw
        WTJGMFpTQkJkWFJvYjNKcGRIa3hGVEFUQmdOVkJBc01ERUZqWTNKbFpHbDBaV1JE
        UVRFWk1CY0cNCkExVUVBd3dRUzBsRFFWOVNUMDlVWDBOQlgwUkZWb0lDQUxZd2N3
        WURWUjBmQkd3d2FqQm9vR2FnWklaaWJHUmhjRG92THpFNU1pNHgNCk5qZ3VNakl3
        TGpFeU5qb3pPRGt2YjNVOVpIQXhjREFzVDFVOVkzSnNaSEFzVDFVOVFXTmpjbVZr
        YVhSbFpFTkJMRTg5UzBsRFFTeEQNClBVdFNQMk5sY25ScFptbGpZWFJsVW1WMmIy
        TmhkR2x2Ymt4cGMzUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRHNYK1ZMaTd0
        SysNCkxucXdiOGFvaVJCVEg5UzJGbHI5aXRqUXQ4R0lmNUdRLzFpTSs0a21pTUxp
        cEp0dS9naGdFY0xjZGtNRjlqVkJaeFFPYUZsSStMUWQNCnFiMzdpa3ExelpEZFhQ
        YzRpMndURHBzY3VkS3pOYWV5LzlmSjN4cExydkgzMHk3eEdZRmwrMjYzcFQvQTM0
        b3FtWm1zY2dvVnRyVE8NCjdDMU1VSU0yajlYVGt3NUFTWVQwL1p6cmkzWWJBbzJE
        ZklVKzZIT1U3V294VlBhSGRIdkxUaEppNXIySEVvZkhQdm1FMkxoYkdjMHINCk9W
        TnloRXlFaGtjZU1MOWdaZlpScjV0bWVrQVNwQTlrMjRlTlZIUFhJa1I3Nmtadkc1
        VHNZallOeFdDSUZMOW13MVg4QkNOUVVjOUMNCmxaNit3cGVHRDNMcHN2cWh0MzFy
        anczRUVBWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
        -----END CERTIFICATE-----
      private-key-base64: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZhRENDQkZDZ0F3SUJBZ0lDQVdrd0RRWUpLb1pJ
        aHZjTkFRRUxCUUF3WlRFTE1Ba0dBMVVFQmhNQ1MxSXhNREF1QmdOVkJBb00NCkowdHZjbVZoSUVsdVpt
        OXliV0YwYVc5dUlFTmxjblJwWm1sallYUmxJRUYxZEdodmNtbDBlVEVWTUJNR0ExVUVDd3dNUVdOamNt
        VmsNCmFYUmxaRU5CTVEwd0N3WURWUVFEREFSemRtTmhNQjRYRFRJME1EVXdOekF4TVRNd01Wb1hEVE0w
        TURVd056QXhNVE13TVZvd2ZqRUwNCk1Ba0dBMVVFQmhNQ1MxSXhEVEFMQmdOVkJBb01CRXRKUTBFeEV6
        QVJCZ05WQkFzTUNteHBZMlZ1YzJWa1EwRXhEekFOQmdOVkJBc00NCkJsTkZVbFpGVWpFUk1BOEdBMVVF
        Q3d3SVMwbERRVlJGVTFReER6QU5CZ05WQkFzTUJsTkZVbFpGVWpFV01CUUdBMVVFQXd3TmRHVnoNCmRH
        TmxjblJmTURVd056Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUs5alVh
        OEtseG1SMFZOY3FpZEwNCk1QaE9WOGJSNE1RWmxkcGE5N01IakFnT201T0RVa0x4cVcrOWRZVS9zMDg3
        akZNbFo2Vjl4RnF3NFFEQng1UEdiRzJrbm9yNEo4eUgNCnZyMnAzY1NlUktjZkN4KzUyK3VVbnpOL1lN
        OEtjNXlPZ2ExcnM3YXJPSFkxaVRKdFJSc3B6Y0RiNzcrZ242ZnVCSGE0WmdCbEdEc2QNCm5kZjlxSm8x
        ajk0TU1MeGRoKzdKUTFkaG1nMnpKQXhqU2F4MktKbjdnT3JPUDFIVDJEZXloWElyVW0rd08zSXp1Ris3
        S3dOQnpEcWINCjJRUjMwYWl6MWxvc2JMRnpFNmJ0R20vOWVIVm9KWFBCSnVxZzNWMnZHNmlwdENXL0lj
        dzZOMWRQWktGOEdwN0F5K3MxSDRtenQ1L0MNCk9zWHBHTzB6UlNuNDBLaUFqRDBDQXdFQUFhT0NBZ2N3
        Z2dJRE1IZ0dBMVVkSUFSeE1HOHdiUVlFVlIwZ0FEQmxNREFHQ0NzR0FRVUYNCkJ3SUJGaVJvZEhSd09p
        OHZkM2QzTG5KdmIzUmpZUzV2Y2k1cmNpOXlZMkV2WTNCekxtaDBiV3d3TVFZSUt3WUJCUVVIQWdJd0pR
        d2oNCjdMQ283SVM0NjR5QUlPeWVrT3VQbWV5d3FDRHNoSnpyc29Uc25ianNwcDNzaEp3d0RnWURWUjBQ
        QVFIL0JBUURBZ1hnTUJ3R0ExVWQNCkVRUVZNQk9nRVFZSktvTWFqSnBFQ2dFQm9BUXdBZ3dBTUNZR0ND
        c0dBUVVGQndFQkJCb3dHREFXQmdnckJnRUZCUWN3QVlZS2IyTnoNCmNDZHpYMVZTVERBZEJnTlZIUTRF
        RmdRVWhjNUJSWTIzQjRLVHFSdzFvSWxTZlNQUkhDNHdnWndHQTFVZEl3U0JsRENCa1lBVU9qa24NCmF3
        aTZjMDExV2NlNTlvRVBPamZtUlJPaGRhUnpNSEV4Q3pBSkJnTlZCQVlUQWt0U01UQXdMZ1lEVlFRS0RD
        ZExiM0psWVNCSmJtWnYNCmNtMWhkR2x2YmlCRFpYSjBhV1pwWTJGMFpTQkJkWFJvYjNKcGRIa3hGVEFU
        QmdOVkJBc01ERUZqWTNKbFpHbDBaV1JEUVRFWk1CY0cNCkExVUVBd3dRUzBsRFFWOVNUMDlVWDBOQlgw
        UkZWb0lDQUxZd2N3WURWUjBmQkd3d2FqQm9vR2FnWklaaWJHUmhjRG92THpFNU1pNHgNCk5qZ3VNakl3
        TGpFeU5qb3pPRGt2YjNVOVpIQXhjREFzVDFVOVkzSnNaSEFzVDFVOVFXTmpjbVZrYVhSbFpFTkJMRTg5
        UzBsRFFTeEQNClBVdFNQMk5sY25ScFptbGpZWFJsVW1WMmIyTmhkR2x2Ymt4cGMzUXdEUVlKS29aSWh2
        Y05BUUVMQlFBRGdnRUJBRHNYK1ZMaTd0SysNCkxucXdiOGFvaVJCVEg5UzJGbHI5aXRqUXQ4R0lmNUdR
        LzFpTSs0a21pTUxpcEp0dS9naGdFY0xjZGtNRjlqVkJaeFFPYUZsSStMUWQNCnFiMzdpa3ExelpEZFhQ
        YzRpMndURHBzY3VkS3pOYWV5LzlmSjN4cExydkgzMHk3eEdZRmwrMjYzcFQvQTM0b3FtWm1zY2dvVnRy
        VE8NCjdDMU1VSU0yajlYVGt3NUFTWVQwL1p6cmkzWWJBbzJEZklVKzZIT1U3V294VlBhSGRIdkxUaEpp
        NXIySEVvZkhQdm1FMkxoYkdjMHINCk9WTnloRXlFaGtjZU1MOWdaZlpScjV0bWVrQVNwQTlrMjRlTlZI
        UFhJa1I3Nmtadkc1VHNZallOeFdDSUZMOW13MVg4QkNOUVVjOUMNCmxaNit3cGVHRDNMcHN2cWh0MzFy
        anczRUVBWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==

management:
  endpoint:
    health:
      show-details: when-authorized  # 인증 필요

eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false

