server:
  port: 8080

spring:
  application:
    name: market-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis.backend.svc.cluster.local
    password: admin1234!
    timeout: 3000ms
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: ${ACTUATOR_USER}  # Kubernetes Secret 필수
      password: ${ACTUATOR_PASSWORD}  # Kubernetes Secret 필수

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external.backend.svc.cluster.local:5432/tiremsdb?prepareThreshold=1
  username: postgres
  password: dev@tire1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

management:
  endpoint:
    health:
      show-details: when-authorized  # 인증 필요

firebase:
  enabled: true
  project-id: tibiseo-eb3d2
  credentials:
    base64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGliaXNlby1lYjNkMiIsCiAgInByaXZhdGVfa2V5X2lkIjogImMwODZlMmVkZGIyNzk4N2RlNDkxYmJiNDg3NzFjNjgzODBhMWMwNWIiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzYwVEROZytmdlAwUkpcblJ5bkhIbmNqd0E1NHRBM0UyNVBjWllYQmh5Qk5PVWZTSFFaVjlVM01VN21SbDVleTNwckNPRmp6bkxFYU1UNmhcbnppVDB1L0VidjRqcnJWb2xFTkdWNXFvR0JSTDEwUEZIdjlVMldIK1RPMUtKQnVLSXNHVEFRU2RVK3pRU1hDVVFcbjMrR1RwaytHQzBEWkZBRHRnUVFwT0dCQU9QNmxxb0djUmVhcWY5N3FXNlNlZkpRc1RIeHpYT1gxSFZydHhGVHdcbmNYZll5T2k5T3k2SllQYVAxM1R6Z1lTUWVKRFF1YmV4UlMxLy9NVytZSjFjYmE1RUs1aVp6L3hwZ3RxcUNOSUpcbmEyU1Y5Q1BvVSs1cldTdXk0Mys2TVRVbWlpc2Rkc2JlTkkzSHpOV0sxVm9rTDB1NmxGMEFOSDZheC90eitMNXhcblc3Vk8vODl2QWdNQkFBRUNnZ0VBVUhPTC84VkJXWisyU1pSUzRvUTFMSGttQWtjUDh1bllxRDQwTnQ1NVE2aGFcblRKcmhRcDFNTHFVVHNpWkZWdXRVWERXbDRPdG12Vy9kbUJMTmlYTnlacys2S0R4VUtNZ3dhY3lYQmRhampxYTNcbmNYMmtWUzRSYXBkT2VPSTFKa1pJYlI3aDBGQUo0YW82OENScDRZcnFqa0JFWWZlaVdxV0g1RFI2QnM1RW81U29cbmFaM0FhOUxGaDhBcWZ4RzBDVW9za21TSDY5bE13K3hSREdzaEJLMEFNeGVRc280QUlYMjBhMHFidHQrZUdBdThcbjA2aEZCN1Avb2p4RGpHcDVWWGh0dW9NUktGeG1tUW5oVkt2blRnQ2RGeitYOUw4S1grWkxRQ1QrU2FTNE0vajFcbjBmaUgwT0xSeHdTUndza2gwK212TzJBQU5aZEM4Q3lhVmVjcWcrcTlBUUtCZ1FEbmI3a2NhRlcrTzBmVmNLbUxcbkdiV1J5RXNUVCs3dGtQdU1TYnNaWUxyYXNZVGdSdi9WN2hTVUMzUktVTURMd0lWZ1VHa2pQaVZqRDV6UmJTbmRcbjlhVi9zeHNQbXlrZlA0aXNuaDMzN0FjYXhPa3g4YlV1UnJNSzJiVlFGM2FXekJwWkM2eENyRW5kb1d3T2d6Ym9cbkpkdG5pRXdKb1UxTDRaVWxseXFrMm9zaDd3S0JnUURPcFNJY054KzJIaGhzaXdGR3g3TmF0QTdEWUQ0ZmMvRGJcbnFCU1hNc2hOanE5VkVmczQwWm5sOThlbGs3NjZMQ3V5dStqVkhObml5ejlieDRScXViUlJ2MDVMUTNsczJmY01cbnJiY2lOb2ZBbWhUajIxQWhpSVVUTVFLOEVDRHNjMklwMjEwdXhGK2RPL3BkSWNGL1E1bHRsd3ViL2E4SllFVGNcbmVCdEYybFdxZ1FLQmdEeWw1R1p6V1BUTzZCWWd2ZTA3d1g4QWM5d051Rmo5QTA1U0MvdXNnNHJIdGtCbm1xZGZcbkNubDVQdkl5a3pOUnNpSDVNSFFSMXc1TWl4VytlNWcweFRmZm9abkhXVkZjL3QzdFdZRWNrd2dLemVsT28rSUtcbm1PU2hCSWlHZlljcTJVUzRjRjNRZEZMbCtFRWRWWWdrVTRpZ0NQMEZEaEp5ZlBrcTBmdjlZVFIxQW9HQkFJTFlcbitZSllQVkk2T0VqeXMvbzNsWkFIbDVtTEpZc1JCU0J4aTZnNTFhK1dlOXNvS2FWT3cxNWt5UnhGTTIzN2JpZ2NcbjZFK1psellPY0s0UzVmd1dYdUdzZTAwWkNwZ3NaRXk0NnM5VkxCeCs5RjlialovT0xFVjhzVGlZRmVEakp2Tk9cbkhmRHhFNElpYW1QeWJlM0J4ak1vZzRkZzJTYmN1SDNKNTZzUmwxRUJBb0dBYWp5RUsyMnV5dTcrQ1BNVk1PWmZcbkJkOXh0aW5aRWN2cllTbnJzeGZpajRlWDRrV1AvUWhqTG50K1pxWWE0RHVTVm5RQlpONzRTRUdoeWxFT1NyWk9cbmdKSVRGYlpJV1UxK2VDK0IzVU5BbVJ1OE1qMTNQZkFFcWl5d0tQTGlyNGd0Qi9iREhTU1BRTGg4eVhkM0JSSU9cbnpGeEVwRmk4aEVmKzVzTWFlUEpJM1p3PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQHRpYmlzZW8tZWIzZDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwNzE5NjczOTc2MDQwOTYyNjc5IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MHRpYmlzZW8tZWIzZDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K

cloud:
  aws:
    s3:
      endpoint: ${S3_ENDPOINT:}
      bucket: ${S3_BUCKET:uploads}
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
cdn:
  base-url: ${CDN_BASE_URL:}

spring:
  servlet:
    multipart:
      max-file-size: 2MB      # 10MB → 2MB
      max-request-size: 2MB

eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false
