server:
  port: 8080

spring:
  application:
    name: notify-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis.backend.svc.cluster.local
    password: authadmin202607!
    timeout: 3000ms
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: ${ACTUATOR_USER}  # Kubernetes Secret 필수
      password: ${ACTUATOR_PASSWORD}  # Kubernetes Secret 필수

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external.backend.svc.cluster.local:5432/tiremsdb?prepareThreshold=1
  username: admin_user
  password: admin@^1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

firebase:
  enabled: true
  project-id: tbiseo-prod
  credentials:
    base64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGJpc2VvLXByb2QiLAogICJwcml2YXRlX2tleV9pZCI6ICIwZjZmYjIwZDUwYjQzNGZhMzM1NzRiOGY0MDVkNWYyZGM4ZDQ3NTk4IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNlZEtvTUFnZ1JtMkwxXG42cjVtMjVKMW1wOGZPcDRWKzNjVVh5dnFCS1lJblp4WnJaWFk0Q1ZIcFozK00wOHExK01oMFJ6MTB6NENBamFlXG5VUXEyZmIwNHEwMFdRSzFKd1oxQXNjTHV2UWdpM0xlQ1JSWWJKQTR1MlNkWGRLdldRVnY1bzM3dDlJbTB1K2k5XG45eDZybnZtT3o5UkovL0RyWno1Z0p6ZVQ2QnhHWkhNeEhKWHJ0ckIrRElTaVJZNk5ocjdTNzVGWmpSa2wrUUtwXG5YRE5DYnR1Qy9qYlduNklselRMK0JaZktIRGphL3VnTDlucGwyZ3ZobVBpeHlpNXBaNXp6NXNYZWVmSkkyUkJUXG50SFRXUGIrYmVRcWpmTExCK2lNYWhrR1N5Q25DWWE4Z3liUE8xcCs1RGNkSjZtK2lId2U2dFNIT2xITWtsQTFGXG5aQmtRYVVWWkFnTUJBQUVDZ2dFQUFJbnhlcU50MjRFYlhDNUZaOElNTmd1SXN1YUlpZWlCM3dXNk1hT1VJcG1qXG5WajlIWHBUWDB1SlNicUV1Mnp5cktSdjErMk1kWUM5ZmVCVzRBekxFTEtUdXFtZGpjbURtSVF0cktZSm15QmMwXG5WRjZVREJOTzBDRlZ1OGNzdnZjWU5PNFN6KzBwR0Z0NDNZMmFGR3F3d05adjBWUU81S0d0SEt2RzdLYjVSeGlMXG5Fb1ZqZkdLWHRCWjBaaG1ELzFtK3lPeFFlb25ST2lWMWc0aGdwY01uM1NsK3VxV3k0V0gvQWp3R09GYllSNHRuXG4vMnkxdi9zV1NCQzNqTVFjVXNJVC82eU5KaFFwaTlWQXhwUTBOeDNTb2s5bVRJdUgrNHlmZmIwcHVqT2E3VGVPXG5iRDJsU3VqZ2RVNHRXdHNzZ2EvaTlyVDRvd0Fxd0hWeDMvT1dpd016QVFLQmdRRFA5bDBNVGJVMHhObzBoeTdpXG5Td2pGZHVjY2h5WXBOaWRWZFZjK1phM1lBNUhPazF5dmRQMzFNeWZCYmNSZ3dPSGM5eUE3YVRRMzUwYndFKzhLXG4xZ3NabDlrVVN0TmRrVENLb3pjc2dHbEtWQ1krVW9NcXNHV2hGTGJLckZzckhEN1ZoWCtieUdCOHdiSDFRQ0oxXG5UdnBqZEp3TDZxTnVLZnhzdFVQK25hL0VHUUtCZ1FERERzY01XM0xYR1FqUnNDWjhlMkx0eUtCYUoxTnEvZ1FXXG5ROXc3Y3oreG9OaGFHekZTQ3M5UVV2LzhEdjVSdW9IUlh4c3M2VFAycmxvMEJta284cHRLazFkM0d2NnRYZ2ZLXG5WV2F6cnJSc3haWi9VRWc4b2dsUVhzTERaQlgzRXMrUkFLa1ZQeUJ6UlBLOWxhM0VtYzQyZDVEdjZXTmptZE1oXG4yMXJNQTJPelFRS0JnRDRwd0dxYkY5MXNNbVdkT3hCOXFXT05SVXdyd2VaenY1STEveHd4dktOamZjUW9ISDUrXG5GQ09sWk83VzV1cWMvV2JWb0JiaVBhK3dQRzRySnpzdi9DVnNWSUZTVkpnVmZGTVVzcnRrcnhSK3p1ZTJObXNlXG5TMks1RkdMRTNvT21iOG5YbSt0dkhCaHV0Y2svb0kwOFRIQktQUkw2MGx0dHhYeWhPbS96cHNTUkFvR0FDMjZWXG5TZXNlS3U4anJpNTF3dnYwUzExajBJVFhoY0RIZW9xVm9NSmJiRXl5QVczd2tROWpJU0VNTWJpclBSMENPTVFyXG5NcEdrWXdQSzg1dWdsQzdMM1M0UGhVS0d4S0JyTW5lWTRsVU43QVlVa1BlaWxETW0rcGZqTUZKd1d4KzJISmgrXG5VR2wzdkduQkZFMXVkc1JRNnE1TlIxSlZhZVA5Rk5IblcyZWpjMEVDZ1lCY1drQ1NEN1lldDFidytSRzc0cnR6XG5nVERBcUZzTUZDTlZsV0FkNXgxcEM4UXMxemZuSll2aHBzOVZMNmY3bkVHNlk3LzVvMU1vK0J6dkxVaWtpNjdhXG5qK2RsVGRhOUg3VkQwK3M0S0FLOU1jUitncDJNN20xZDAvbWlGRnNIOEVLbUtESTZQWURjWndNRVFCSVh1V25rXG51RVhhQ0RScTMyODN5UGF6dS9VcWxnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1mYnN2Y0B0YmlzZW8tcHJvZC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTA5NjkxNDE0ODU3ODAyNTgxNDAiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZic3ZjJTQwdGJpc2VvLXByb2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K

management:
  endpoint:
    health:
      show-details: when-authorized  # 인증 필요

eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false
