server:
  port: 8080

spring:
  application:
    name: game-mng-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 16379
    host: dev-elasticache-replication-group.ikmdkh.ng.0001.apn2.cache.amazonaws.com

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external.backend.svc.cluster.local:5432/tiremsdb?charSet=UTF-8&prepareThreshold=1&serverTimezone=Asia/Seoul
  username: postgres
  password: dev@tire1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 Actuator 엔드포인트 활성화
eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: cenlots2024-discoveryserver-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
