server:
  port: 8080

spring:
  application:
    name: tire-mg-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis.backend.svc.cluster.local
    password: authadmin202607!
    timeout: 3000ms
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: ${ACTUATOR_USER}  # Kubernetes Secret 필수
      password: ${ACTUATOR_PASSWORD}  # Kubernetes Secret 필수

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external.backend.svc.cluster.local:5432/tiremsdb?prepareThreshold=1
  username: admin_user
  password: admin@^1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

notify:
  server:
    base-url: http://notify-service.backend.svc.cluster.local:8080
    send-path: /notify-service/api/v1/alarm/notify/send

firebase:
  enabled: true
  project-id: tibiseo-eb3d2
  credentials:
    base64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGliaXNlby1lYjNkMiIsCiAgInByaXZhdGVfa2V5X2lkIjogImMwODZlMmVkZGIyNzk4N2RlNDkxYmJiNDg3NzFjNjgzODBhMWMwNWIiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzYwVEROZytmdlAwUkpcblJ5bkhIbmNqd0E1NHRBM0UyNVBjWllYQmh5Qk5PVWZTSFFaVjlVM01VN21SbDVleTNwckNPRmp6bkxFYU1UNmhcbnppVDB1L0VidjRqcnJWb2xFTkdWNXFvR0JSTDEwUEZIdjlVMldIK1RPMUtKQnVLSXNHVEFRU2RVK3pRU1hDVVFcbjMrR1RwaytHQzBEWkZBRHRnUVFwT0dCQU9QNmxxb0djUmVhcWY5N3FXNlNlZkpRc1RIeHpYT1gxSFZydHhGVHdcbmNYZll5T2k5T3k2SllQYVAxM1R6Z1lTUWVKRFF1YmV4UlMxLy9NVytZSjFjYmE1RUs1aVp6L3hwZ3RxcUNOSUpcbmEyU1Y5Q1BvVSs1cldTdXk0Mys2TVRVbWlpc2Rkc2JlTkkzSHpOV0sxVm9rTDB1NmxGMEFOSDZheC90eitMNXhcblc3Vk8vODl2QWdNQkFBRUNnZ0VBVUhPTC84VkJXWisyU1pSUzRvUTFMSGttQWtjUDh1bllxRDQwTnQ1NVE2aGFcblRKcmhRcDFNTHFVVHNpWkZWdXRVWERXbDRPdG12Vy9kbUJMTmlYTnlacys2S0R4VUtNZ3dhY3lYQmRhampxYTNcbmNYMmtWUzRSYXBkT2VPSTFKa1pJYlI3aDBGQUo0YW82OENScDRZcnFqa0JFWWZlaVdxV0g1RFI2QnM1RW81U29cbmFaM0FhOUxGaDhBcWZ4RzBDVW9za21TSDY5bE13K3hSREdzaEJLMEFNeGVRc280QUlYMjBhMHFidHQrZUdBdThcbjA2aEZCN1Avb2p4RGpHcDVWWGh0dW9NUktGeG1tUW5oVkt2blRnQ2RGeitYOUw4S1grWkxRQ1QrU2FTNE0vajFcbjBmaUgwT0xSeHdTUndza2gwK212TzJBQU5aZEM4Q3lhVmVjcWcrcTlBUUtCZ1FEbmI3a2NhRlcrTzBmVmNLbUxcbkdiV1J5RXNUVCs3dGtQdU1TYnNaWUxyYXNZVGdSdi9WN2hTVUMzUktVTURMd0lWZ1VHa2pQaVZqRDV6UmJTbmRcbjlhVi9zeHNQbXlrZlA0aXNuaDMzN0FjYXhPa3g4YlV1UnJNSzJiVlFGM2FXekJwWkM2eENyRW5kb1d3T2d6Ym9cbkpkdG5pRXdKb1UxTDRaVWxseXFrMm9zaDd3S0JnUURPcFNJY054KzJIaGhzaXdGR3g3TmF0QTdEWUQ0ZmMvRGJcbnFCU1hNc2hOanE5VkVmczQwWm5sOThlbGs3NjZMQ3V5dStqVkhObml5ejlieDRScXViUlJ2MDVMUTNsczJmY01cbnJiY2lOb2ZBbWhUajIxQWhpSVVUTVFLOEVDRHNjMklwMjEwdXhGK2RPL3BkSWNGL1E1bHRsd3ViL2E4SllFVGNcbmVCdEYybFdxZ1FLQmdEeWw1R1p6V1BUTzZCWWd2ZTA3d1g4QWM5d051Rmo5QTA1U0MvdXNnNHJIdGtCbm1xZGZcbkNubDVQdkl5a3pOUnNpSDVNSFFSMXc1TWl4VytlNWcweFRmZm9abkhXVkZjL3QzdFdZRWNrd2dLemVsT28rSUtcbm1PU2hCSWlHZlljcTJVUzRjRjNRZEZMbCtFRWRWWWdrVTRpZ0NQMEZEaEp5ZlBrcTBmdjlZVFIxQW9HQkFJTFlcbitZSllQVkk2T0VqeXMvbzNsWkFIbDVtTEpZc1JCU0J4aTZnNTFhK1dlOXNvS2FWT3cxNWt5UnhGTTIzN2JpZ2NcbjZFK1psellPY0s0UzVmd1dYdUdzZTAwWkNwZ3NaRXk0NnM5VkxCeCs5RjlialovT0xFVjhzVGlZRmVEakp2Tk9cbkhmRHhFNElpYW1QeWJlM0J4ak1vZzRkZzJTYmN1SDNKNTZzUmwxRUJBb0dBYWp5RUsyMnV5dTcrQ1BNVk1PWmZcbkJkOXh0aW5aRWN2cllTbnJzeGZpajRlWDRrV1AvUWhqTG50K1pxWWE0RHVTVm5RQlpONzRTRUdoeWxFT1NyWk9cbmdKSVRGYlpJV1UxK2VDK0IzVU5BbVJ1OE1qMTNQZkFFcWl5d0tQTGlyNGd0Qi9iREhTU1BRTGg4eVhkM0JSSU9cbnpGeEVwRmk4aEVmKzVzTWFlUEpJM1p3PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQHRpYmlzZW8tZWIzZDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwNzE5NjczOTc2MDQwOTYyNjc5IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9maXJlYmFzZS1hZG1pbnNkay1mYnN2YyU0MHRpYmlzZW8tZWIzZDIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K

cloud:
  aws:
    s3:
      endpoint: ${S3_ENDPOINT:}
      bucket: ${S3_BUCKET:uploads}
      access-key: ${S3_ACCESS_KEY:}
      secret-key: ${S3_SECRET_KEY:}
cdn:
  base-url: ${CDN_BASE_URL:}

file:
  upload:
    path: /app/uploads

molit:
  vehicle:
    api:
      url: https://linkstg.car365.go.kr/hub/kotsa
      service-id: AC1_ZA85_01
      cvmis-apikey: 7AA75EC3-917067ED-689C6D47-96345CA9
      private-key-password: test1234!
      public-key-base64: MIIFaDCCBFCgAwIBAgICAWkwDQYJKoZIhvcNAQELBQAwZTELMAkGA1UEBhMCS1IxMDAuBgNVBAoMJ0tvcmVhIEluZm9ybWF0aW9uIENlcnRpZmljYXRlIEF1dGhvcml0eTEVMBMGA1UECwwMQWNjcmVkaXRlZENBMQ0wCwYDVQQDDARzdmNhMB4XDTI0MDUwNzAxMTMwMVoXDTM0MDUwNzAxMTMwMVowfjELMAkGA1UEBhMCS1IxDTALBgNVBAoMBEtJQ0ExEzARBgNVBAsMCmxpY2Vuc2VkQ0ExDzANBgNVBAsMBlNFUlZFUjERMA8GA1UECwwIS0lDQVRFU1QxDzANBgNVBAsMBlNFUlZFUjEWMBQGA1UEAwwNdGVzdGNlcnRfMDUwNzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK9jUa8KlxmR0VNcqidLMPhOV8bR4MQZldpa97MHjAgOm5ODUkLxqW+9dYU/s087jFMlZ6V9xFqw4QDBx5PGbG2knor4J8yHvr2p3cSeRKcfCx+52+uUnzN/YM8Kc5yOga1rs7arOHY1iTJtRRspzcDb77+gn6fuBHa4ZgBlGDsdndf9qJo1j94MMLxdh+7JQ1dhmg2zJAxjSax2KJn7gOrOP1HT2DeyhXIrUm+wO3IzuF+7KwNBzDqb2QR30aiz1losbLFzE6btGm/9eHVoJXPBJuqg3V2vG6iptCW/Icw6N1dPZKF8Gp7Ay+s1H4mzt5/COsXpGO0zRSn40KiAjD0CAwEAAaOCAgcwggIDMHgGA1UdIARxMG8wbQYEVR0gADBlMDAGCCsGAQUFBwIBFiRodHRwOi8vd3d3LnJvb3RjYS5vci5rci9yY2EvY3BzLmh0bWwwMQYIKwYBBQUHAgIwJQwj7LCo7IS464yAIOyekOuPmeywqCDshJzrsoTsnbjspp3shJwwDgYDVR0PAQH/BAQDAgXgMBwGA1UdEQQVMBOgEQYJKoMajJpECgEBoAQwAgwAMCYGCCsGAQUFBwEBBBowGDAWBggrBgEFBQcwAYYKb2NzcCdzX1VSTDAdBgNVHQ4EFgQUhc5BRY23B4KTqRw1oIlSfSPRHC4wgZwGA1UdIwSBlDCBkYAUOjknawi6c011Wce59oEPOjfmRROhdaRzMHExCzAJBgNVBAYTAktSMTAwLgYDVQQKDCdLb3JlYSBJbmZvcm1hdGlvbiBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkxFTATBgNVBAsMDEFjY3JlZGl0ZWRDQTEZMBcGA1UEAwwQS0lDQV9ST09UX0NBX0RFVoICALYwcwYDVR0fBGwwajBooGagZIZibGRhcDovLzE5Mi4xNjguMjIwLjEyNjozODkvb3U9ZHAxcDAsT1U9Y3JsZHAsT1U9QWNjcmVkaXRlZENBLE89S0lDQSxDPUtSP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3QwDQYJKoZIhvcNAQELBQADggEBADsX+VLi7tK+Lnqwb8aoiRBTH9S2Flr9itjQt8GIf5GQ/1iM+4kmiMLipJtu/ghgEcLcdkMF9jVBZxQOaFlI+LQdqb37ikq1zZDdXPc4i2wTDpscudKzNaey/9fJ3xpLrvH30y7xGYFl+263pT/A34oqmZmscgoVtrTO7C1MUIM2j9XTkw5ASYT0/Zzri3YbAo2DfIU+6HOU7WoxVPaHdHvLThJi5r2HEofHPvmE2LhbGc0rOVNyhEyEhkceML9gZfZRr5tmekASpA9k24eNVHPXIkR76kZvG5TsYjYNxWCIFL9mw1X8BCNQUc9ClZ6+wpeGD3Lpsvqht31rjw3EEAY=
      private-key-base64: MIIE8DAaBggqgxqMmkQBDzAOBAhJhwA6r2im1wICBAAEggTQ29XnVgdsqJdCVQejATlUTyQ4xlOVyJa4xkVDVhaYQBi4S1zBVwXTBv91CGudHKrSZxEbjJ2UUJYZ1XGiSdHmhGmTyXhJLOKDiElDu4SsY158U02CsxsxQeNyGWz3j3IW4eNApt1EOglEJbgPur1vW+vzJdYOHPnLPI5Fw7qyXL0xUGvf2sthrpBiOu0CYDA3TM4TE+zL+yLMYMGgr/RU+1c1NFyi5jTfnmG7LmdcbCwBHwgFcIS5aOGqwFD4wB5vtL0Vl2YR8vKNZx3gwrCBVOtdfCfBDuH27TEG2luiVmowepbe+W22AX3yClS425FP+M+N5mbkcQwgIXom4EQsFG9z/FQTs3GQCZ6VUSbVSGJIocgj2tBhWHfar929S56S5iFjPOnaIB3QG/wEAfAStYaGhLdYGthxoRltCbchJXsjLxrvj5tnKL2QFErWNLFSmGSL+xyOqIMBlCSO+C/q45EAQNvcsn7Ul/ELoqzLAPUhv1X/JHS4obugYlG16zhQly5xIdJG1oFgAnA89/0IWEpqLGvOsP3zjgozMp6u1c9el1UoV362ocmzR6qJ8rZrAHsmtTrghVldlYbe9aXDsgSCT0nG0kAhwywr/xkFJTvV+kKJQV81HX4/u1GaTrdhrwt88NwvMTEDJipgrpPNQCIf9vjNaqsfAwM5g3juLZX8RB/AZqU9mAOdmyt7XSs3abP9ANTjfsjE/y4Trt5ZtvuvT+qm0z7H+QiyakTyP01uhQlzd3UAQxW+GX5+pzNGUH4p0CkBTxylnGCKwGOBs4JBzEi/rqwibRmrwMsHhyxNkuJlRakkmPu8azutRLTK8R4FPnSbIPSQEhLMdkt11fOwj0dEgb7c22PgKHsNOzk7IJ3w1d19mM6TT2PoqPv+tut0GBII5n0l5eQmdqjYKNzW9aH04GGkxl5s7roBbjtbubBdL+xfQcYjDsAfCSkXXVTyYXweLAxY6Jp9Z5ySVnnkCCJ10Njc7tSxs35GLRNdy0n1NNhwZtDTDkPmAI8ZPJqgwBbmVRlS0mRPuzN5N1dr+2KS/E1ppeXcGtEHESx6RbAR0I0PuDsQf4hcWKZwOMbXbyhZXjpXzwlJgSKQepEMlTffHa0iyELI8Ssj9xnaH+PSgmFvLqmGW43FXLCr/2adUC9deGb48p83oLgK3qG3q7DRkTIsvaC9LxSdefP3Q4WqObLmuAL5TPxKy5g/wSHdo1tBkHTr7lk4cD5SmkYXSm8AxMsuwCd4RmiasBYiZbuYrnWCgmo+izq8H2pENIxxU3if3k6Wqk/QLvyUtdQDlliF76jkCoU9bVr0cl70+N83Fb9qh+ZYrJtkwsJz/03RQkX/ojaf1uZ+bNsvF3j4JH/Pr/Spf0pmhcqCGmAIQAPGUSQUpxxy/puABkWRV5hX/t5emBOIF6hT7Er2kBWzkieV12gB3S2M0wOck61CFXIMOfR3X9lCGYbDKboI10SDmGbvJkHq5zXncUPxBSy/VgeYXVHtqZ5RQj0pnnxiRLXAy5UOSxzOOr4yc+yKO0vchMho6Bgram+mLDyFjk0Qdfro8tGr7LieIgP7UoibYRH/E//cDmNUDr8khHfzzK7qBugZy3OyGBh+LBgpdTmYalg+Kk/Fy33sDGHVCh0=
      log-response: false

management:
  endpoint:
    health:
      show-details: when-authorized  # 인증 필요

eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false
