server:
  port: 8080

spring:
  application:
    name: tire-mg-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis.backend.svc.cluster.local
    timeout: 3000ms
  thymeleaf:
    check-template-location: false
  security:
    user:
      name: ${ACTUATOR_USER}  # Kubernetes Secret 필수
      password: ${ACTUATOR_PASSWORD}  # Kubernetes Secret 필수

jdbc:
  url: jdbc:log4jdbc:postgresql://postgresql-external.backend.svc.cluster.local:5432/tiremsdb?prepareThreshold=1
  username: postgres
  password: dev@tire1234!
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

management:
  endpoint:
    health:
      show-details: when-authorized  # 인증 필요

eureka:
  client:
    register-with-eureka: false  # 자신을 Eureka에 등록하지 않음
    fetch-registry: false


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: cenlots2024-discoveryserver-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
