server:
  port: 7010

spring:
  application:
    name: tire-mg-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      on-profile: local
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
  security:
    user:
      name: admin
      password: admin
  redis:
  cluster:
    nodes:
      - 172.21.128.1:6371
      - 172.21.128.1:6372
      - 172.21.128.1:6373
    pool:
      max-active: 10
      max-idle: 10
      min-idle: 2
    max-redirects: 3
  timeout: 500
#  redis:
#    sentinel:
#      master: mymaster              # Sentinel 설정에서 감시하는 마스터 이름
#      nodes: 172.21.128.1:26379,172.21.128.1:26380,172.21.128.1:26381
#    timeout: 5000                   # 타임아웃(ms)
#    lettuce:
#      shutdown-timeout: 100          # Lettuce 종료 타임아웃(ms)
#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#    port: 6666
#    host: localhost

jdbc:
  url: jdbc:postgresql://localhost:5432/tiremsdb?charSet=UTF-8&prepareThreshold=1
  username: postgres
  password: user1234
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

eureka:
  instance:
    prefer-ip-address: true
    hostname: cenlots2024-discoveryserver-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
